package com.example.miniproyecto_sudoku.controller.adapter;

import javafx.event.EventHandler;
import javafx.scene.input.KeyEvent;

/**
 * Adapter responsible for handling keyboard events in the Sudoku board.
 * This class processes user input, validates allowed keys, and delegates
 * actions for inserting or clearing values in the selected cell.
 *
 * @author Juan José Morera Gómez
 * @author Frank Leonardo Silva Castillo
 * @version 1.0
 * @since 1.0
 */
public class SudokuKeyAdapter implements EventHandler<KeyEvent>, ISudokuCellInputHandler {

    /**
     * Row index of the currently selected cell.
     */
    private int selectedRow;

    /**
     * Column index of the currently selected cell.
     */
    private int selectedCol;

    /**
     * Action executed when a value is entered into a cell.
     */
    private TriConsumer onInput;

    /**
     * Action executed when a cell is cleared.
     */
    private java.util.function.BiConsumer<Integer, Integer> onClear;

    /**
     * Functional interface used to handle cell input operations.
     */
    @FunctionalInterface
    public interface TriConsumer {

        /**
         * Performs an action using the specified row, column, and value.
         *
         * @param row row of the selected cell.
         * @param col column of the selected cell.
         * @param value value entered in the cell.
         */
        void accept(int row, int col, int value);
    }

    /**
     * Creates a new SudokuKeyAdapter with no selected cell.
     */
    public SudokuKeyAdapter() {
        this.selectedRow = -1;
        this.selectedCol = -1;
    }

    /**
     * Sets the currently selected cell coordinates.
     *
     * @param row row of the selected cell.
     * @param col column of the selected cell.
     */
    public void setSelectedCell(int row, int col) {
        this.selectedRow = row;
        this.selectedCol = col;
    }

    /**
     * Sets the action executed when a value is entered into a cell.
     *
     * @param onInput action responsible for processing the input value.
     */
    public void setOnInput(TriConsumer onInput) {
        this.onInput = onInput;
    }

    /**
     * Sets the action executed when a cell is cleared.
     *
     * @param onClear action responsible for clearing the selected cell.
     */
    public void setOnClear(java.util.function.BiConsumer<Integer, Integer> onClear) {
        this.onClear = onClear;
    }

    /**
     * Handles keyboard events generated by the user.
     * Processes valid numeric input and clear operations for the selected cell.
     *
     * @param event keyboard event triggered by the user.
     */
    @Override
    public void handle(KeyEvent event) {
        if (selectedRow == -1 || selectedCol == -1) return;

        String key = event.getText();

        switch (event.getCode()) {
            case BACK_SPACE:
            case DELETE:
                handleClear(selectedRow, selectedCol);
                break;
            default:
                if (key.matches("[1-6]")) {
                    handleInput(selectedRow, selectedCol, Integer.parseInt(key));
                }
                break;
        }
    }

    /**
     * Handles the insertion of a value into a specific cell.
     *
     * @param row row of the selected cell.
     * @param col column of the selected cell.
     * @param value value entered in the cell.
     */
    @Override
    public void handleInput(int row, int col, int value) {
        if (onInput != null) {
            onInput.accept(row, col, value);
        }
    }

    /**
     * Handles clearing the content of a specific cell.
     *
     * @param row row of the selected cell.
     * @param col column of the selected cell.
     */
    @Override
    public void handleClear(int row, int col) {
        if (onClear != null) {
            onClear.accept(row, col);
        }
    }
}